### ISSUE TITLE
Support Postgres 13.0 to allow pg_dump 

### ISSUE THREAD

**Issue by amanymous-net** [turbot/steampipe-postgres-fdw#88]
Postgres 13.0 adds a `--include-foreign-data` option to `pg_dump`. This will allow steampipe to create backups at a point in time from all the sources defined in the config.

**Comment by e-gineer** [comment]
Thanks @amanymous-net - I agree it would be great to pg_dump the foreign tables from Steampipe via Postgres 13. (We're also interested in the [simpler JSON syntax for SQL](https://blog.crunchydata.com/blog/better-json-in-postgres-with-postgresql-14) coming in Postgres 14.)

Some notes / background:

1. We use an embedded postgres binary from [the zonky project](https://github.com/zonkyio/embedded-postgres-binaries).
2. We use 12.1 simply because it was the latest zonky version at the time.
3. We have a [build script to package it for download](https://github.com/turbot/steampipe/blob/main/.github/workflows/buildDBImage.yml) from the steampipe CLI. Basically we repackage it as an OCI image for download like we download plugins etc.
4. We'd need to plan any version change carefully to ensure a smooth upgrade for existing CLI users.

So, we're definitely supportive of moving the postgres version forward, but solutions need to work through and test the items above - particularly the upgrade path.
